/*
4º - Criar uma Nova Tabela de Endereço com os Seguintes Campos (2.0): 
  ---> Id do Endereço - Sequence incrementando numa progressão de 1 - Como Campo Padrão. - Também deve ser a Chave Primária;
  ---> Código do Cliente: Chave Estrangeira de Cliente;
  ---> CEP - Campo de Texto; 
  ---> Logradouro- Campo de Texto;

  ---> Numero - Campo de Texto;

  ---> Complemento - Campo de Texto;

  ---> Bairro - Campo de Texto;

  ---> Cidade - Campo de Texto;

  ---> UF - Chave estrangeira da tabela Estado (Campo UF);

  ---> Tipo Endereço - 'P' - Principal, 'C' - Cobrança, 'T' - Endereço de Trabalho;
  ---> Data Cadastro - Data e Hora - Padrão Data Atual;
  ---> Observações - Campo Texto;
Ao final da Criação, A tabela deve ser capaz de receber o Cadastro de Endereço para qualquer cliente Cadastrado.
*/

CREATE TABLE HACARLOS.ENDERECO (
	ID_ENDERECO NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
	COD_CLIENTE NUMBER NOT NULL,
	CEP VARCHAR2(8),
	LOGRADOURO VARCHAR2(255),
	NUMERO VARCHAR2(10),
	COMPLEMENTO VARCHAR2(255),
	BAIRRO VARCHAR2(255),
	CIDADE VARCHAR2(255),
	UF VARCHAR2(3),
	TIPO_ENDERECO VARCHAR2(1),
	DT_CADASTRO TIMESTAMP DEFAULT SYSDATE,
	OBSERVACOES VARCHAR2(255),
	CONSTRAINT pk_endereco PRIMARY KEY (ID_ENDERECO),
	CONSTRAINT fk_endereco_cliente FOREIGN KEY (COD_CLIENTE) REFERENCES HACARLOS.CLIENTE(ID_CLIENTE),
	CONSTRAINT fk_endereco_estado FOREIGN KEY (UF) REFERENCES HACARLOS.ESTADO (UF)
); 

INSERT INTO HACARLOS.ENDERECO (
	COD_CLIENTE,
	CEP,
	LOGRADOURO ,
	NUMERO,
	BAIRRO,
	CIDADE,
	UF,
	TIPO_ENDERECO ,
	OBSERVACOES 
)
VALUES (
	3,
	'69421342',
	'RUA MAGRATEA',
	'42',
	'NEBULA CABEÇA DE CAVALO',
	'SOULIANIS',
	'SP',
	'P',
	'CASA DE SLARTIBARTFAST'
)

INSERT INTO HACARLOS.ENDERECO (
	COD_CLIENTE,
	CEP,
	LOGRADOURO ,
	NUMERO,
	BAIRRO,
	CIDADE,
	UF,
	TIPO_ENDERECO ,
	OBSERVACOES 
)
VALUES (
	2,
	'98765432',
	'RUA FIM',
	'1980',
	'FIM DO UNIVERSO',
	'MILIWAYS',
	'MT',
	'T',
	'SE PODE VER GNAB GIB'
)
